import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import {
  EVENT_ORDER,
  formatSecondsAsMmSs,
  type EventKey,
} from "@/lib/aft-scoring";
import type { AnalyzeResponseBody } from "@/lib/analyze-types";

function isTimedEvent(key: EventKey): boolean {
  return key === "sdc" || key === "plk" || key === "twoMR";
}

function formatRawDisplay(key: EventKey, raw: number): string {
  if (isTimedEvent(key)) return formatSecondsAsMmSs(raw);
  return String(raw);
}

function genderLabel(g: AnalyzeResponseBody["gender"] | undefined): string {
  if (g === "male") return "Male";
  if (g === "female") return "Female";
  return "—";
}

function statusLabel(s: "pass" | "borderline" | "fail"): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function addFooters(doc: jsPDF, margin: number): void {
  const footer = "Generated by traintopass.com";
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(0, 0, 0);
    const h = doc.internal.pageSize.getHeight();
    doc.text(footer, margin, h - 8);
  }
}

function appendWrappedText(
  doc: jsPDF,
  text: string,
  y: number,
  margin: number,
  lineHeight: number,
  fontSize: number,
  fontStyle: "normal" | "bold"
): number {
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const maxWidth = pageW - 2 * margin;
  doc.setFont("helvetica", fontStyle);
  doc.setFontSize(fontSize);
  doc.setTextColor(0, 0, 0);
  const lines = doc.splitTextToSize(text || "—", maxWidth);
  let cy = y;
  for (const line of lines) {
    if (cy > pageH - 18) {
      doc.addPage();
      cy = margin;
    }
    doc.text(line, margin, cy);
    cy += lineHeight;
  }
  return cy;
}

export function downloadTrainingPlanPdf(data: AnalyzeResponseBody): void {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const margin = 14;
  let y = margin;

  doc.setTextColor(0, 0, 0);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  const pageW = doc.internal.pageSize.getWidth();
  const title = "Train to Pass — Your 4-Week AFT Training Plan";
  const titleLines = doc.splitTextToSize(title, pageW - 2 * margin);
  for (const line of titleLines) {
    doc.text(line, margin, y);
    y += 7;
  }
  y += 4;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(`Age group: ${data.ageGroup ?? "—"}`, margin, y);
  y += 6;
  doc.text(`Gender: ${genderLabel(data.gender)}`, margin, y);
  y += 6;
  doc.text(`Total score: ${data.totalScore} / 500`, margin, y);
  y += 10;

  const rows: string[][] = [];
  for (const key of EVENT_ORDER) {
    const ev = data.events.find((e) => e.key === key);
    if (!ev) continue;
    rows.push([
      ev.label,
      formatRawDisplay(ev.key, ev.raw),
      String(ev.score),
      statusLabel(ev.status),
    ]);
  }

  autoTable(doc, {
    startY: y,
    head: [["Event", "Raw Score", "Points", "Status"]],
    body: rows,
    theme: "plain",
    styles: {
      font: "helvetica",
      fontSize: 9,
      textColor: [0, 0, 0],
      lineColor: [0, 0, 0],
      lineWidth: 0.1,
    },
    headStyles: {
      fillColor: [255, 255, 255],
      textColor: [0, 0, 0],
      fontStyle: "bold",
      lineWidth: 0.1,
    },
    bodyStyles: { fillColor: [255, 255, 255] },
    margin: { left: margin, right: margin, top: margin, bottom: 16 },
  });

  const lastY = (
    doc as unknown as { lastAutoTable?: { finalY: number } }
  ).lastAutoTable?.finalY;
  y = (typeof lastY === "number" ? lastY : y) + 10;

  const sections: { title: string; body: string }[] = [
    { title: "Week 1", body: data.weeks.week1 },
    { title: "Week 2", body: data.weeks.week2 },
    { title: "Week 3", body: data.weeks.week3 },
    { title: "Week 4", body: data.weeks.week4 },
  ];

  const pageH = doc.internal.pageSize.getHeight();
  for (const sec of sections) {
    if (y > pageH - 30) {
      doc.addPage();
      y = margin;
    }
    y = appendWrappedText(doc, sec.title, y, margin, 6, 11, "bold");
    y += 2;
    y = appendWrappedText(doc, sec.body, y, margin, 4.5, 9, "normal");
    y += 6;
  }

  addFooters(doc, margin);

  doc.save("traintopass-plan.pdf");
}
