import { jsPDF } from "jspdf";
import type { GeneralProgramStored } from "@/lib/general-program-types";

function addFooters(doc: jsPDF, margin: number): void {
  const footer = "Generated by traintopass.com";
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(0, 0, 0);
    const h = doc.internal.pageSize.getHeight();
    doc.text(footer, margin, h - 8);
  }
}

function appendWrappedText(
  doc: jsPDF,
  text: string,
  y: number,
  margin: number,
  lineHeight: number,
  fontSize: number,
  fontStyle: "normal" | "bold"
): number {
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const maxWidth = pageW - 2 * margin;
  doc.setFont("helvetica", fontStyle);
  doc.setFontSize(fontSize);
  doc.setTextColor(0, 0, 0);
  const lines = doc.splitTextToSize(text || "—", maxWidth);
  let cy = y;
  for (const line of lines) {
    if (cy > pageH - 18) {
      doc.addPage();
      cy = margin;
    }
    doc.text(line, margin, cy);
    cy += lineHeight;
  }
  return cy;
}

export function downloadGeneralProgramPdf(data: GeneralProgramStored): void {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const margin = 14;
  let y = margin;

  doc.setTextColor(0, 0, 0);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  const pageW = doc.internal.pageSize.getWidth();
  const title = "Train to Pass — 8-Week General Training Program";
  const titleLines = doc.splitTextToSize(title, pageW - 2 * margin);
  for (const line of titleLines) {
    doc.text(line, margin, y);
    y += 7;
  }
  y += 4;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  const genDate = new Date(data.generatedAt).toLocaleString();
  doc.text(`Generated: ${genDate}`, margin, y);
  y += 6;
  doc.text(`Goal: ${data.goal}`, margin, y);
  y += 6;
  doc.text(`Training days/week: ${data.trainingDays}`, margin, y);
  y += 6;
  doc.text(`Equipment: ${data.equipment}`, margin, y);
  y += 6;
  doc.text(`Level: ${data.fitnessLevel}`, margin, y);
  y += 6;
  if (data.limitations.trim()) {
    doc.text(`Limitations: ${data.limitations.trim()}`, margin, y);
    y += 6;
  }
  y += 4;

  appendWrappedText(
    doc,
    data.markdown,
    y,
    margin,
    4.5,
    9,
    "normal"
  );

  addFooters(doc, margin);

  doc.save("traintopass-general-program.pdf");
}
