import { jsPDF } from "jspdf";

function addFooters(doc: jsPDF, margin: number): void {
  const footer = "Generated by traintopass.com";
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(0, 0, 0);
    const h = doc.internal.pageSize.getHeight();
    doc.text(footer, margin, h - 8);
  }
}

function appendWrappedText(
  doc: jsPDF,
  text: string,
  y: number,
  margin: number,
  lineHeight: number,
  fontSize: number,
  fontStyle: "normal" | "bold"
): number {
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const maxWidth = pageW - 2 * margin;
  doc.setFont("helvetica", fontStyle);
  doc.setFontSize(fontSize);
  doc.setTextColor(0, 0, 0);
  const lines = doc.splitTextToSize(text || "—", maxWidth);
  let cy = y;
  for (const line of lines) {
    if (cy > pageH - 18) {
      doc.addPage();
      cy = margin;
    }
    doc.text(line, margin, cy);
    cy += lineHeight;
  }
  return cy;
}

export function downloadEnlistmentPlanPdf(markdown: string, titleExtra?: string): void {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const margin = 14;
  let y = margin;

  doc.setTextColor(0, 0, 0);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  const pageW = doc.internal.pageSize.getWidth();
  const title = `Train to Pass — 12-Week Enlistment Prep${titleExtra ? ` — ${titleExtra}` : ""}`;
  const titleLines = doc.splitTextToSize(title, pageW - 2 * margin);
  for (const line of titleLines) {
    doc.text(line, margin, y);
    y += 7;
  }
  y += 6;

  y = appendWrappedText(doc, markdown.replace(/\*\*/g, ""), y, margin, 5, 10, "normal");
  addFooters(doc, margin);
  doc.save("aft-enlistment-12-week-plan.pdf");
}
