ALTER TABLE users ADD COLUMN IF NOT EXISTS current_rank TEXT DEFAULT 'E-1';
ALTER TABLE users ADD COLUMN IF NOT EXISTS rank_updated_at TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN IF NOT EXISTS activity_streak INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_active_date DATE;
